### ISSUE TITLE
Create FamaFrench.Rdata file, documenting accordingly  

### ISSUE THREAD

**Issue by JustinMShea** [JustinMShea/ExpectedReturns#10]
As part of this, you can call data(FamaFrench) in the vignette

**Comment by JustinMShea** [comment]
While you were talking, I added the FamaFrench data. So @vi-to , I also gave you a good head start on documenting the data as well on the FF3.monthly.R file in the R folder. 

So, update the descriptions for MKT.RF, SMB, HML, and RF. 

Also, borrow descriptive content from the Fama French website to describe in the "@section"
I would also

**Comment by vi-to** [comment]
Fetching from `data/` is great. Documentation will follow along soon. Thanks Justin!

**Comment by JustinMShea** [comment]
Nice work, very thorough. 

However, I noticed you removed the bullet points I added, describing concisely and compactly, the frequency, range, and time stamp of when the data was saved. This is a best practice is documentation data for packages, so that users can quickly understand the data set. Please add these back under the @format, and fill in the bullet points for descriptions for MKT.RF, SMB, HML, and RF. Also, make sure to note the data type for each item, ie type `numeric`.

https://github.com/JustinMShea/ExpectedReturns/commit/4401ce3c67e3266d7977dce92fdec512d444b3ce

**Comment by vi-to** [comment]
Thanks for pointing this out @JustinMShea. A summary sounds helpful for navigating the document.
