### ISSUE TITLE
Create Parser for Prof. Lubos Pastor's Liquidity Factor Data

### ISSUE THREAD

**Issue by vi-to** [JustinMShea/ExpectedReturns#12]
The replication data set provided by Prof. Lubos Pastor contains data on the "liquidity factor". 

The data he shares contain the replication data set for the pioneering work Pastor-Stambaugh (2003). Also, given the importance of the (aggregate) liquidity factor, it has been studied in the more recent literature of interest such as Asness-Moskowitz-Pedersen (2013).

Here's a quick insight on aggregate liquidity:

![aggregate_liquidity](https://user-images.githubusercontent.com/42696897/84798578-6c7ced00-affb-11ea-9472-ef67363ef717.png)

Lastly, since Prof. Pastor seems to regularly update data shared, it may well represent a source for the convenient `GetFactors()`. See #7.

**See also:** https://github.com/JustinMShea/ExpectedReturns/wiki/Data-sources#replication-data-sets

**Comment by JustinMShea** [comment]
As discussed, we can get to it later, but for now, it can wait.
