### ISSUE TITLE
Vignette: Value-oriented equity selection: The Devil in HML's Details 

### ISSUE THREAD

**Issue by JustinMShea** [JustinMShea/ExpectedReturns#13]
### Value factors to compare with **HML**

 _[The Devil in HML’s Details (Asness and Frazzini, 2013)](https://www.aqr.com/Insights/Datasets/The-Devil-in-HMLs-Details-Factors-Daily)_

### Data

https://github.com/JustinMShea/ExpectedReturns/blob/master/inst/parsers/Devil-in-HML-Details.R

### Background

 _[Investment Performance of Common Stocks in Relation to Their Price-Earnings Ratios: A Test of the Efficient Market (S. Basu, 1977)](https://www.jstor.org/stable/2326304?seq=1#metadata_info_tab_contents)_

_[The  Cross-Section of Expected Stock Returns (Fama, French, 1992)](https://www.jstor.org/stable/pdf/2326304.pdf?casa_token=OfXGQ5yHguUAAAAA:ByDPItQUpoabkWLtlgdyjqImUv0Y3CHDTo64ozZWLZ5OhZKLp63LmKUgxAOsZmnYkrLUSTJAFZ6R2Kq_h8CyJEd_IJ7qDjMa7gf8H1C5J4aT_Zi_qw)_

Expected Returns (Ch 12), Engle (Ch 10).

**Comment by JustinMShea** [comment]
I've added a brief markdown template with sections to help guide you. A data parser has been started to get the factors from AQR. Copy/pasta the code into the vignette, and build associated transformations, and merge the factors against the individual equity samples found in FactorAnalytics, similar to what you did in the first vignette. Ping us with questions.

**Comment by JustinMShea** [comment]
@vi-to In addition to the code comment I made under commit @1e75089, break up your code into chunks, similar to what I did in #4 . Have a data loading and processing section, then a new code chunk for `fitFfm` and then for `plm`. Then, you and we, can more easily isolate errors in each section.

**Comment by erolbicero** [comment]
@JustinMShea @vi-to  I finished editing the parsing script, the file now knits (at the time of this writing), however the build still fails for me.

**Comment by jaymon0703** [comment]
I believe this issue is done. We have a working example of the HML Devil replication, and any additional work required to get the vignette into a "publishable" state (not that that is the objective i dont think) can be added to this issue once it is re-opened, or a new issue opened. Hope that is suitable to everyone.

**Comment by JustinMShea** [comment]
We need to transform this into a static vignette as suggested in issue #20. As part of this, in the data section, we should not `source` parsers, but fully display the parser code within the vignette. This will allow users to reproduce everything from this single vignette.

**Comment by JustinMShea** [comment]
Refactor into FactorAnalytics, and cleanup code comments
