### ISSUE TITLE
Add a (minimal) financial data scraper/parser

### ISSUE THREAD

**Issue by vi-to** [JustinMShea/ExpectedReturns#7]
We need an helper function to easily download financial research data sets from several sources and conveniently import them in `R`.

For example, publicly available resources include the well know library maintained by Prof. Kenneth French (http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html). These data sets are very important, for educational, research and investment purposes. More often than not, they constitute comparison benchmarks for other models internationally. Specifically, for our project they represent an essential ingredient to develop and show functionality.

Likewise, resources should include replication data sets such as those made publicly available by financial companies such as AQR (https://www.aqr.com/Insights/Datasets). It should be remarked how beneficial is that they are freely available, especially because they pair perfectly with one of our main references, Dr. Ilmanen's book.

**Please note:** There is now a marginally overlapping issue, #8. The new Issue is aimed at parsers to download and import specific data sets from AQR, therefore in the meanwhile it constitutes the reference for this matter. However, since the Company has historically provided updated data sets from time to time, users may wish to get fresh data when possible and this will hopefully receive some attention in `GetFactors()` when appropriate. In this case this Issue is being referenced.

**See also:** https://github.com/JustinMShea/ExpectedReturns/wiki/Data-sources for a list of data sets we are potentially interested in and might possibly use in the course of this project.

**Comment by JustinMShea** [comment]
Fama-French Factors complete
